language: cpp
compiler: gcc
install: make

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++-7 libgtest-dev cmake curl python3 python3-pip

before_install:
  - pip3 install git+https://github.com/gcovr/gcovr.git
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

script:
  - cd $TRAVIS_BUILD_DIR
  - make CXX=g++-7
  - make CXX=g++-7 test
  - ./neocortex_test
  - gcovr --coveralls coveralls.json
  - echo -n "{\"service_name\": \"travis-ci\", \"service_job_id\":\"$TRAVIS_JOB_ID\", " > coveralls2.json
  - tail -c+2 coveralls.json >> coveralls.json
  - curl -X POST -H "Content-Type: application/json" -d @coveralls2.json https://coveralls.io/api/v1/jobs
