language: cpp
compiler: gcc
install: make

addons:
  apt:
    packages: g++-6 libgtest-dev

before_install:
  - pip install --user cpp-coveralls

script:
  - CXX=g++-6 make

after_install:
  - CXX=g++-6 make test
  - ./neocortex_test
  - coveralls --exclude test
