language: cpp
compiler: gcc
install: make

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++-7 libgtest-dev cmake

before_install:
  - pip install --user cpp-coveralls
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

script:
  - cd $TRAVIS_BUILD_DIR
  - make CXX=g++-7
  - make CXX=g++-7 test
  - ./neocortex_test
  - coveralls --exclude test --gcov-options '\-r'
